[package]
name = "fuzzer1531"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
rand = "0.8"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
faker = "1.2"